function [Gravity,Thrust] = AUVKickInMatrix(in1)
%AUVKICKINMATRIX
%    [GRAVITY,THRUST] = AUVKICKINMATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Feb-2021 21:09:38

epsilon1 = in1(5,:);
epsilon2 = in1(6,:);
epsilon3 = in1(7,:);
eta = in1(4,:);
z = in1(3,:);
t2 = epsilon1.^2;
t3 = epsilon2.^2;
t4 = epsilon1.*epsilon3.*2.0;
t5 = epsilon2.*epsilon3.*2.0;
t6 = epsilon1.*eta.*2.0;
t7 = epsilon2.*eta.*2.0;
t9 = sqrt(2.0);
t10 = z.*(4.0e+1./3.0);
t8 = -t7;
t11 = t10-2.0;
t12 = t5+t6;
t13 = t9./2.0;
t17 = t9.*(1.1e+1./4.0e+2);
t14 = erf(t11);
t15 = t4+t8;
t16 = -t13;
t18 = -t17;
t19 = t14.*1.85e-2;
t20 = t19+1.85e-2;
Gravity = [epsilon1.*epsilon3.*(-6.66099e+2)+epsilon2.*eta.*6.66099e+2+t15.*t20.*9.79038e+3;epsilon2.*epsilon3.*(-6.66099e+2)-epsilon1.*eta.*6.66099e+2+t12.*t20.*9.79038e+3;t2.*6.66099e+2+t3.*6.66099e+2-t20.*(t2.*2.0+t3.*2.0-1.0).*9.79038e+3-3.330495e+2;t2.*(-1.998297)-t3.*1.998297+epsilon2.*epsilon3.*1.7984673e+1+epsilon1.*eta.*1.7984673e+1+t12.*t20.*9.79038e+2+9.991485e-1;t2.*(-6.66099e-1)-t3.*6.66099e-1-epsilon1.*epsilon3.*1.7984673e+1+epsilon2.*eta.*1.7984673e+1-t15.*t20.*9.79038e+2+3.330495e-1;epsilon1.*epsilon3.*(-1.998297)-epsilon2.*epsilon3.*6.66099e-1-epsilon1.*eta.*6.66099e-1+epsilon2.*eta.*1.998297];
if nargout > 1
    Thrust = reshape([t13,t16,0.0,t17,t17,3.400838131990407e+2.*(-1.0./1.0e+3),t13,t13,0.0,t18,t17,6.83593446428504e+1.*(-1.0./2.0e+2),t13,t16,0.0,t17,t17,3.387462176910615e+2./1.0e+3,t13,t13,0.0,t18,t17,3.37017803684019e+2./1.0e+3,0.0,0.0,1.0,8.1e+1./5.0e+2,-1.805e-1,0.0,0.0,0.0,-1.0,-8.1e+1./5.0e+2,-7.3e+1./4.0e+2,0.0,0.0,0.0,1.0,-3.9e+1./2.5e+2,7.3e+1./4.0e+2,0.0,0.0,0.0,-1.0,3.9e+1./2.5e+2,1.805e-1,0.0],[6,8]);
end
