classdef ComputeTrajectory < ros.Message
    %ComputeTrajectory MATLAB implementation of proc_control_matlab/ComputeTrajectory
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2021 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'proc_control_matlab/ComputeTrajectory' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a0e69ebc8e828630834852258d0c3acb' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Compute
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Compute'} % List of non-constant message properties
        ROSPropertyList = {'compute'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ComputeTrajectory(msg)
            %ComputeTrajectory Construct the message object ComputeTrajectory
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function compute = get.Compute(obj)
            %get.Compute Get the value for property Compute
            compute = logical(obj.JavaMessage.getCompute);
        end
        
        function set.Compute(obj, compute)
            %set.Compute Set the value for property Compute
            validateattributes(compute, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'ComputeTrajectory', 'Compute');
            
            obj.JavaMessage.setCompute(compute);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Compute = obj.Compute;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Compute = strObj.Compute;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Compute = obj.Compute;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.proc_control_matlab.ComputeTrajectory.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.proc_control_matlab.ComputeTrajectory;
            obj.reload(strObj);
        end
    end
end
