classdef ThrustLogging < ros.Message
    %ThrustLogging MATLAB implementation of proc_control/ThrustLogging
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2021 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'proc_control/ThrustLogging' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '84102cbd792e4637747efca5a0331017' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        ThrustAxe
        ThrustThruster
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ThrustAxe', 'ThrustThruster'} % List of non-constant message properties
        ROSPropertyList = {'thrust_axe', 'thrust_thruster'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ThrustLogging(msg)
            %ThrustLogging Construct the message object ThrustLogging
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function thrustaxe = get.ThrustAxe(obj)
            %get.ThrustAxe Get the value for property ThrustAxe
            javaArray = obj.JavaMessage.getThrustAxe;
            array = obj.readJavaArray(javaArray, 'single');
            thrustaxe = single(array);
        end
        
        function set.ThrustAxe(obj, thrustaxe)
            %set.ThrustAxe Set the value for property ThrustAxe
            if ~isvector(thrustaxe) && isempty(thrustaxe)
                % Allow empty [] input
                thrustaxe = single.empty(0,1);
            end
            
            validateattributes(thrustaxe, {'numeric'}, {'vector'}, 'ThrustLogging', 'ThrustAxe');
            
            javaArray = obj.JavaMessage.getThrustAxe;
            array = obj.writeJavaArray(thrustaxe, javaArray, 'single');
            obj.JavaMessage.setThrustAxe(array);
        end
        
        function thrustthruster = get.ThrustThruster(obj)
            %get.ThrustThruster Get the value for property ThrustThruster
            javaArray = obj.JavaMessage.getThrustThruster;
            array = obj.readJavaArray(javaArray, 'single');
            thrustthruster = single(array);
        end
        
        function set.ThrustThruster(obj, thrustthruster)
            %set.ThrustThruster Set the value for property ThrustThruster
            if ~isvector(thrustthruster) && isempty(thrustthruster)
                % Allow empty [] input
                thrustthruster = single.empty(0,1);
            end
            
            validateattributes(thrustthruster, {'numeric'}, {'vector'}, 'ThrustLogging', 'ThrustThruster');
            
            javaArray = obj.JavaMessage.getThrustThruster;
            array = obj.writeJavaArray(thrustthruster, javaArray, 'single');
            obj.JavaMessage.setThrustThruster(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ThrustAxe = obj.ThrustAxe;
            cpObj.ThrustThruster = obj.ThrustThruster;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ThrustAxe = strObj.ThrustAxe;
            obj.ThrustThruster = strObj.ThrustThruster;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ThrustAxe = obj.ThrustAxe;
            strObj.ThrustThruster = obj.ThrustThruster;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.proc_control.ThrustLogging.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.proc_control.ThrustLogging;
            obj.reload(strObj);
        end
    end
end
